import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Form Title",
  description: "Form generated by Form Factory",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="contents">{children}</div>;
}
